config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'bookings#app_index'
  #root 'rooms#index'
  get 'users' => 'users#index'
  get 'bookings' => 'bookings#index'
  get 'available' => 'bookings#available'
end

app/models/booking.rb
class MoreThanValidator < ActiveModel::Validator
  def validate(record)
    if record.startdate < Time.new
      record.errors[:base] << "Time start cannot be earlier than current time"
    end
    if record.enddate <= record.startdate + 1740 
      record.errors[:base] << "Time end cannot be earlier than or equal to current time or lesser than 30mins of booking"
    end

    # Resolution is 1min
    start = record.startdate - 60
    final = record.enddate + 60

    # If current room booking exists startdate that is within the input startdate and end date within startdate

    # if current booking start date and enddate coincides with any booking within the day, reject
    # if any start date coincides with any booking within the day but end date outside, reject
    # if any end date conincides with any booking within the day but start date outside, reject
    # @overlap = Booking.where('room_id = ? AND (startdate BETWEEN ? AND ?) AND (enddate BETWEEN ? AND ?)', record.room_id, start, final, start, final)
    @overlap = Booking.where('room_id = ? AND (startdate <= ? AND enddate >= ?) OR (startdate >= ? AND enddate <= ?) OR (startdate BETWEEN ? AND ?) OR (enddate BETWEEN ? AND ?)', record.room_id, start, final, start, final, start, final, start, final)
    unless @overlap.empty?
      record.errors[:base] << "Room is unavailable at this time and day"
    end
    @overlapuser = Booking.where('user_id = ? AND (startdate BETWEEN ? AND ?) AND (enddate BETWEEN ? AND ?)', record.user_id, start, final, start, final)
    unless @overlapuser.empty?
      record.errors[:base] << "User has another booking at this time and day"
    end
  end
end

class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates_associated :room
  validates_associated :user
  validates_with MoreThanValidator, fields:[:startdate, :enddate]
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new

    @today = Date.today
    @tomorrow = Date.today + 1
    @twodayslater = Date.today + 2
    booked = Booking.joins(:room).where('(startdate BETWEEN ? AND ?) OR (enddate BETWEEN ? AND ?)', @today, @tomorrow, @today, @tomorrow).order('rooms.location')
    booked_tomorrow = Booking.joins(:room).where('(startdate BETWEEN ? AND ?) OR (enddate BETWEEN ? AND ?)', @tomorrow, @twodayslater, @tomorrow, @twodayslater).order('rooms.location')

    @datatoday = []
    booked.each do |booking|
      b = [booking.room.location, booking.startdate, booking.enddate]
      @datatoday.push(b)
    end
    
    @datatomorrow = []
    booked_tomorrow.each do |booking|
      b = [booking.room.location, booking.startdate, booking.enddate]
      @datatomorrow.push(b)
    end
    if @datatoday.empty? 
      @datatoday.push(["No Bookings Yet", Date.today, Date.today])
    end
    if @datatomorrow.empty? 
      @datatomorrow.push(["No Bookings Yet", Date.today, Date.today])
    end
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    @today = Date.today
    @tomorrow = Date.today + 1
    @twodayslater = Date.today + 2
    booked = Booking.joins(:room).where('(startdate BETWEEN ? AND ?) OR (enddate BETWEEN ? AND ?)', @today, @tomorrow, @today, @tomorrow).order('rooms.location')
    booked_tomorrow = Booking.joins(:room).where('(startdate BETWEEN ? AND ?) OR (enddate BETWEEN ? AND ?)', @tomorrow, @twodayslater, @tomorrow, @twodayslater).order('rooms.location')

    @datatoday = []
    booked.each do |booking|
      b = [booking.room.location, booking.startdate, booking.enddate]
      @datatoday.push(b)
    end
    
    @datatomorrow = []
    booked_tomorrow.each do |booking|
      b = [booking.room.location, booking.startdate, booking.enddate]
      @datatomorrow.push(b)
    end
    if @datatoday.empty? 
      @datatoday.push(["No Bookings Yet", Date.today, Date.today])
    end
    if @datatomorrow.empty? 
      @datatomorrow.push(["No Bookings Yet", Date.today, Date.today])
    end

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:user_id, :room_id, :startdate, :enddate)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_available.html.erb
<div class="jumbotron">
    <h2> Bookings from <%= @today %> to <%= @tomorrow %> </h2>
</div>
<div class="jumbotron jumbotron-form">
    <%= timeline @datatoday, height: "200px"%>
</div>
<div class="jumbotron">
    <h2> Bookings from <%= @tomorrow %> to <%= @twodayslater %> </h2>
</div>
<div class="jumbotron jumbotron-form">
    <%= timeline @datatomorrow, height: "200px" %>
</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h4>
      <ul>
        <% booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="jumbotron jumbotron-form text-align-left">
    <div class="row">
      <div class="col-sm-3">
        <div class="form-group">
          <%= form.label :user_id %>
          <% options = options_from_collection_for_select(User.all, 'id', 'name') %>  
          <%= form.select :user_id, options, {}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
        </div>
      </div>
      
      <div class="col-sm-3">
        <div class="form-group">
          <%= form.label :room_id %>
          <% options = options_from_collection_for_select(Room.all, 'id', 'location') %>
          <%= form.select :room_id, options, {}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="form-group">
          <%= form.label :startdate %>
          <%= form.datetime_select :startdate, { order:[:day,:month,:year] }, { class: "form-control" } %>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="form-group">
          <%= form.label :enddate %>
          <%= form.datetime_select :enddate, { order:[:day,:month,:year], default: 30.minutes.from_now }, { class: "form-control" } %>
        </div>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-sm btn-primary text-dark" %>
  </div>
<% end %>

app/views/bookings/app_index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
    <h1>Facility Booking Application</h1>
</div>
<br>
<%= link_to("Book a room", { controller: "bookings", action: "index" }, class: "btn btn-sm btn-primary text-dark") %>
<br>
<%= link_to("Create a room [ Only for admins ]", { controller: "rooms", action: "index" }, class: "btn btn-sm btn-primary text-dark") %>
<br>
<%= link_to("Create a user [ Only for admins ]", { controller: "users", action: "index" }, class: "btn btn-sm btn-primary text-dark") %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking, class: "btn btn-sm btn-primary text-dark" %> |
<%= link_to 'Back', bookings_path, class: "btn btn-sm btn-primary text-dark" %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1>Bookings</h1>
</div>

<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th>Booking Name</th>
      <th>User Department</th>
      <th>Location</th>
      <th>Capacity</th>
      <th>Classification</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user.name %></td>
        <td><%= booking.user.department %></td>
        <td><%= booking.room.location %></td>
        <td><%= booking.room.capacity %></td>
        <td><%= booking.room.classification %></td>
        <td><%= booking.startdate %></td>
        <td><%= booking.enddate %></td>
        <td><%= link_to 'Show', booking, class:"btn text-secondary btn-sm btn-primary" %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking), class:"btn text-secondary btn-sm btn-primary"%></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn text-secondary btn-sm btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path, class:"btn text-secondary btn-sm btn-primary" %>
<br>
<%= link_to("Back to main", { controller: "bookings", action: "app_index" }, class:"btn text-secondary btn-sm btn-primary") %>

app/views/bookings/new.html.erb
<div class="jumbotron">
    <h1>New Booking</h1>
</div>
<%= render 'form', booking: @booking %>
<%= link_to 'Back', bookings_path, class: "btn btn-sm btn-primary text-dark" %>
<br>
<br>
<%= render 'available', datatoday: @datatoday, datatomorrow: @datatomorrow %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron jumbotron-form text-align-left">
  <div class="row">
    <div class="col-sm-3">
      <strong>Booking Name:</strong>
      <%= @booking.user.name %>
    </div>

    <div class="col-sm-2">
      <strong>User Department:</strong>
      <%= @booking.user.department %>
    </div>

    <div class="col-sm-2">
      <strong>Location:</strong>
      <%= @booking.room.location %>
    </div>

    <div class="col-sm-2">
      <strong>Capacity:</strong>
      <%= @booking.room.capacity %>
    </div>

    <div class="col-sm-3">
      <strong>Classification:</strong>
      <%= @booking.room.classification %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3">
      <strong>Startdate:</strong>
      <%= @booking.startdate %>
    </div>

    <div class="col-sm-3">
      <strong>Enddate:</strong>
      <%= @booking.enddate %>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_booking_path(@booking), class: "btn btn-sm btn-primary text-dark" %> 
<%= link_to 'Back', bookings_path, class: "btn btn-sm btn-primary text-dark" %>